/*
 * This source file was generated by the Gradle 'init' task
 */
package apcsa_q4.project;

import org.junit.jupiter.api.Test;

import apcsa_q4.project.Main.Main;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Main classUnderTest = new Main();
        assertEquals(classUnderTest.test(), 2);
    }
}
